    ORG 00H
MAIN:
    MOV P3, #0FFH ;setup port 3 as input
    SETB P2.3 ;setup EOC pin as input
    CLR P0.0 ;clear error sig

;DISPLAY ROUTINE
INIT_DISPLAY:
    MOV A, #38H;8 bit mode configuration
    ACALL COMMAND
    MOV A, #80H
    ACALL COMMAND
    ;MOV A, #0EH DISPLAY ON CURSOR BLINKING
    MOV A, #0CH ;DISPLAY ON CURSOR OFF
    ACALL COMMAND
    MOV A, #01H
    ACALL COMMAND
    ;DISPLAY STUFF
    ;MOV DPTR, #TEMP_TXT ;LOAD TEMPERATURE TEXT ON SCREEN
    ; After INIT_DISPLAY
    CLR P2.5
    CLR P2.6
    CLR P2.7 ;SET LATCH TO TEMPERATURE READ
    ACALL ADC_CONV
    ACALL TEMP_READ

DISP_STRING:
    CLR A
    MOVC A, @A + DPTR
    ACALL DATAC
    INC DPTR
    JNZ DISP_STRING
    RET
    ;ACALL TEMP_READ

TEMP_READ:
    MOV DPTR, #TEMP_TXT ;LOAD TEMPERATURE TEXT ON SCREEN
    ;Read adc on channel 
    ACALL DISP_STRING
    SETB P2.5 ;LSB
    CLR P2.6 ;MSB
    CLR P2.7 ;MMSB
    ;ACALL DELAY_DOT142
    ACALL PRESENT_DATA
    ;DISP_STRING DEG CELCIUS
    ACALL DELAY_DOT142
    
    ACALL CLEAR_SCR
    ACALL HUMID_READ

HUMID_READ:
    MOV DPTR, #HUMID_TXT ;LOAD HUMIDITY TEXT ON SCREEN
    ACALL DISP_STRING
    CLR P2.5 ;LSB
    CLR P2.6 ;MSB
    CLR P2.7 ;MMSB
    ACALL PRESENT_DATA
    ;DISP_STRING %
    ACALL DELAY_DOT142
    
    ACALL CLEAR_SCR
    ACALL TEMP_READ
    
PRESENT_DATA:
    ACALL ADC_CONV
    MOV B, #2
    MUL AB       ; A = ADC × 2
    MOV B, #10
    DIV AB       ; A = tens, B = units
    MOV R0, A
    MOV R2, B
    MOV R7, A ; save value of A temporarily
    ACALL SW_BOT_LN ; switch cursor to bottom line
    MOV A, R7 ; restore value of A from R7
    ADD A, #30H
    ACALL DATAC
    MOV A, B
    ADD A, #30H
    ACALL DATAC
    ACALL SW_TOP_LN ; switch cursor to top line
    RET

;HELPER SUBROUTINES HELPER SUBROUTINES
;HELPER SUBROUTINES HELPER SUBROUTINES
ERR:
    SETB P0.0
    ACALL DELAY_DOT142
    SJMP ERR

SW_TOP_LN:
    MOV A, #80H
    ACALL COMMAND
    RET

SW_BOT_LN:
    MOV A, #0C0H
    ACALL COMMAND
    RET

CLEAR_SCR:
    MOV A, #01H
    ACALL COMMAND
    RET

ADC_CONV:
    ; Trigger first conversion to warm up ADC
    ACALL DELAY_DOT142
    SETB P2.2
    ACALL DELAY_DOT142
    CLR P2.2
    ACALL DELAY_DOT142
    SETB P2.1
    ACALL DELAY_DOT142
    CLR P2.1
    ACALL DELAY_DOT142
WAIT_EOC:
    JB P2.3, WAIT_EOC
    SETB P2.4
    ACALL DELAY_DOT142
    MOV A, P3 ; dummy read
    CLR P2.4
    RET

COMMAND:
    MOV P1, A
    CLR P0.7
    SETB P2.0
    ACALL DELAY_DOT142
    CLR P2.0
    ACALL DELAY_DOT142
    RET

DATAC:
    MOV P1, A
    SETB P0.7
    SETB P2.0
    ACALL DELAY_02
    CLR P2.0
    ACALL DELAY_02
    RET

DELAY_DOT142:
    MOV R0, #0FFH
AGAIN:
    MOV R1, #0FFH
HERE:
    DJNZ R1, HERE
    DJNZ R0, AGAIN
    RET

DELAY_02:
    MOV R0, #03H
AGAIN_2:
    MOV R1, #03H
HERE_2:
    DJNZ R1, HERE_2
    DJNZ R0, AGAIN_2
    RET

TEMP_TXT:
    DB "TEMPERATURE", 0
HUMID_TXT:
    DB "HUMIDITY", 0
DEG_CEL:
    DB ""

    END